- name: Add flathub repo
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    
- name: Install xca from flatpak
  community.general.flatpak:
    name: io.github.chris2511.xca
    state: present