#!/bin/sh 

exec tail -n +3 $0

# RECOVERY 
menuentry "Recovery" --class recovery {
  insmod fat
  insmod chain
  search --no-floppy --fs-uuid --set=root CB0C-AAA5
  chainloader /EFI/boot/bootx64.efi
}
~    
