---
- name: Update packages
  ansible.builtin.apt:
    update_cache: true

- name: Install packages
  ansible.builtin.apt:
    state: latest
    pkg: "{{ item }}"
    update_cache: false
  loop:    
    - tree
    - tmux
    - byobu
    - python3-debian
    - gpg    