---
- name: Make sure the folder exists (Debian, Ubuntu)
  file:
    path: /usr/local/share/ca-certificates
    state: directory

# Note that the .crt is actually a .pem renamed
- name: Copy IES Grao CA certificate (Debian, Ubuntu)
  copy:
    src: gvacertintermedio.crt
    dest: "/usr/local/share/ca-certificates/gvacertintermedio.crt"
  register: result

- name: Copy GVA intermediate certificate (Debian, Ubuntu)
  copy:
    src: root-ca.crt
    dest: "/usr/local/share/ca-certificates/root-ca.crt"
  register: result

- name: Update CA Trust (Debian, Ubuntu)
  command: update-ca-certificates
  when: result is changed