- name: Clone a repo with separate git directory
  ansible.builtin.git:
    repo: 'https://github.com/ptoribi/lightning.git'
    dest: /tmp/lightning

- name: Install lighning if /usr/local/bin/lighting does not exist
  ansible.builtin.command:
    cmd: /tmp/lightning/install
    creates: /usr/local/bin/lightning


- name: allow students to run lighning as sudo
  community.general.sudoers:
    name: lightning
    state: present
    group: students
    runas: 'ALL:ALL'
    commands: /usr/local/bin/lightning

- name: allow ALU_FP_A3 to run lighning as sudo
  community.general.sudoers:
    name: lightning
    state: present
    group: ALU_FP_A3
    runas: 'ALL:ALL'
    commands: /usr/local/bin/lightning



#sudo bash -c "echo 'ALL ALL=(ALL) NOPASSWD: $(dirname $(readlink -f $(which lightning)))"/lightning"' > /etc/sudoers.d/lightning"

#sudo bash -c "echo '%students ALL=(ALL) NOPASSWD: $(dirname $(readlink -f $(which lightning)))"/lightning"' >> /etc/sudoers.d/lightning"
#sudo bash -c "echo '%ALU_FP_A3 ALL=(ALL) NOPASSWD: $(dirname $(readlink -f $(which lightning)))"/lightning"' >> /etc/sudoers.d/lightning"
#sudo bash -c "echo '%Docente_A3 ALL=(ALL) NOPASSWD: $(dirname $(readlink -f $(which lightning)))"/lightning"' >> /etc/sudoers.d/lightning"