---
- name: Update packages
  ansible.builtin.apt:
    update_cache: true

- name: Install dependencies packages
  ansible.builtin.apt:
    state: latest
    pkg: "{{ item }}"
    update_cache: false
  loop:    
    - bridge-utils
    - libxml2-utils
    - evince
    - git
    - x11-utils
    - libc-bin
    - coreutils
    - iproute2
    - iptables
    - mawk
    - python3
    - python3-pip
    - docker.io


- name: Clone a repo with separate git directory
  ansible.builtin.git:
    repo: 'https://github.com/ptoribi/lightning.git'
    dest: /tmp/lightning

- name: Install lighning if /usr/local/bin/lighting does not exist
  ansible.builtin.command:
    cmd: /tmp/lightning/install
    creates: /usr/local/bin/lightning

- name: allow ALL to run lighning as sudo
  community.general.sudoers:
    name: lightning
    state: present
    user: ALL
    runas: 'ALL:ALL'
    commands: /usr/local/bin/lightning







#sudo bash -c "echo 'ALL ALL=(ALL) NOPASSWD: $(dirname $(readlink -f $(which lightning)))"/lightning"' > /etc/sudoers.d/lightning"

#sudo bash -c "echo '%students ALL=(ALL) NOPASSWD: $(dirname $(readlink -f $(which lightning)))"/lightning"' >> /etc/sudoers.d/lightning"
#sudo bash -c "echo '%ALU_FP_A3 ALL=(ALL) NOPASSWD: $(dirname $(readlink -f $(which lightning)))"/lightning"' >> /etc/sudoers.d/lightning"
#sudo bash -c "echo '%Docente_A3 ALL=(ALL) NOPASSWD: $(dirname $(readlink -f $(which lightning)))"/lightning"' >> /etc/sudoers.d/lightning"