- name: Install wireshark
  ansible.builtin.apt:
    update_cache: no
    state: latest
    pkg: wireshark

- name: allow ALL run wireshard as sudo
  community.general.sudoers:
    name: wireshark
    state: present
    user: ALL
    runas: 'ALL:ALL'
    commands: /usr/bin/wireshark
