default-remote: incus-os
remotes:
  examen:
    addr: https://192.168.82.205:8443
    protocol: incus
    public: true
  examen_auth:
    addr: https://192.168.82.205:8443
    auth_type: tls
    project: default
    protocol: incus
    public: false
  images:
    addr: https://images.linuxcontainers.org
    protocol: simplestreams
    public: true
  incus-os:
    addr: https://192.168.10.230:8443
    auth_type: tls
    project: default
    protocol: incus
    public: false
  local:
    addr: unix://
    protocol: incus
    public: false
aliases: {}
defaults:
  list_format: ""
  console_type: ""
  console_spice_command: ""
